/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Daos.DaoCompra;
import Daos.DaoOrden;
import Principal.Orden;
import Tablas.TablaVerOrdenes;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Joaquin Martinez
 */
public class VerOrdenes extends javax.swing.JFrame {

    private DaoOrden daoOrden;
    private DaoCompra daoCompra;
    private ArrayList<Orden> ordenes;
    private TablaVerOrdenes tvo;

    private Orden ordenSeleccionada;

    private VerOrden2 vistaDetalleOrden;

    /**
     * Creates new form Prueba
     */
    public VerOrdenes() {
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            vistaDetalleOrden = new VerOrden2();
            tvo = new TablaVerOrdenes();
            daoOrden = new DaoOrden();
            daoCompra = new DaoCompra();
            ordenes = daoOrden.obtenerTodas();
            tvo.llenarTablaProductosOrdenados(jTable1, ordenes);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(VerOrdenes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolverMenu = new javax.swing.JButton();
        btnVerDatosOrden = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnEditarOrden = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVolverMenu.setText("Volver al menú principal");
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });

        btnVerDatosOrden.setText("Ver orden");
        btnVerDatosOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDatosOrdenActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Número de la orden", "Estado", "Fecha de compra", "Precio total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnEditarOrden.setText("Editar orden");
        btnEditarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarOrdenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnEditarOrden)
                        .addGap(38, 38, 38)
                        .addComponent(btnVerDatosOrden)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnPagar)
                        .addGap(66, 66, 66)
                        .addComponent(btnVolverMenu)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerDatosOrden)
                    .addComponent(btnCancelar)
                    .addComponent(btnPagar)
                    .addComponent(btnVolverMenu)
                    .addComponent(btnEditarOrden))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerDatosOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDatosOrdenActionPerformed
        try {
            ordenSeleccionada = this.obtenerOrdenSeleccionada();
            this.mostrarVistaDeDetalleDeLaOrden();
        } catch (ParseException | SQLException ex) {
            Logger.getLogger(VerOrdenes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVerDatosOrdenActionPerformed

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        MenuPrincipal volverMenu = new MenuPrincipal();
        volverMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    private Orden obtenerOrdenSeleccionada() throws ParseException, ArrayIndexOutOfBoundsException {
        //int numeroOrden, String statusOden, Date fechaCompra, double precioTotal
        int id = Integer.valueOf(this.jTable1.getModel().getValueAt(this.jTable1.getSelectedRow(), 0).toString());
        String estado = this.jTable1.getModel().getValueAt(this.jTable1.getSelectedRow(), 1).toString();
        String fechaCompra = this.jTable1.getModel().getValueAt(this.jTable1.getSelectedRow(), 2).toString();
        double precio = Double.valueOf(this.jTable1.getModel().getValueAt(this.jTable1.getSelectedRow(), 3).toString());
        return new Orden(id, estado, fechaCompra, precio);
    }

    private void mostrarVistaDeDetalleDeLaOrden() throws SQLException {
        daoCompra.cargarProductosDeLaOrden(ordenSeleccionada);
        vistaDetalleOrden.setOrden(ordenSeleccionada);
        vistaDetalleOrden.initView();
        vistaDetalleOrden.setVisible(true);
        this.dispose();
    }

    private void pagarOCancelarOrden(boolean pagar) {
        try {
            ordenSeleccionada = this.obtenerOrdenSeleccionada();
            if (ordenSeleccionada.getStatusOrden().equalsIgnoreCase("EN CURSO")) {
                ordenSeleccionada.setStatusOrden(pagar ? "PAGADA" : "CANCELADA");
                daoOrden.setOrden(ordenSeleccionada);
                daoOrden.actualizarEstadoDeLaOrden();
                this.mostrarVistaDeDetalleDeLaOrden();

            } else {
                JOptionPane.showMessageDialog(null, "Para pagar o cancelar una orden, debe tener como estado EN CURSO");
            }

        } catch (SQLException | ParseException ex) {
            Logger.getLogger(VerOrdenes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        this.pagarOCancelarOrden(true);
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.pagarOCancelarOrden(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarOrdenActionPerformed
        try {
            this.ordenSeleccionada = this.obtenerOrdenSeleccionada();
            if (this.ordenSeleccionada.getStatusOrden().equalsIgnoreCase("EN CURSO")) {
                CrearOrden c = new CrearOrden();
                c.setVisible(true);
                this.daoCompra.cargarProductosDeLaOrden(ordenSeleccionada);
                c.setOrdenParaEditar(ordenSeleccionada);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Para editar una orden, debe tener como estado EN CURSO");
            }

        } catch (ParseException | SQLException ex) {
            Logger.getLogger(VerOrdenes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditarOrdenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerOrdenes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditarOrden;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnVerDatosOrden;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
